const actions = {
  GET_ALL_CAKES: 'GET_ALL_CAKES',
  SET_ALL_CAKES: 'SET_ALL_CAKES',
  Add_CAKES:'Add_CAKES',
  Add_CAKES_STATUS:'Add_CAKES_STATUS',
  GET_SINGLE_CAKEDETAILS:'GET_SINGLE_CAKEDETAILS',
  SET_SINGLE_CAKEDETAILS:'SET_SINGLE_CAKEDETAILS'
};

export default actions;
